
Repository=xml

ProductsBin=/Users/zagreansonia/Desktop/lab3/data/product.bin
OrdersBin=/Users/zagreansonia/Desktop/lab3/data/order.bin

ProductsTxt=/Users/zagreansonia/Desktop/MAP/labs/a3-soniazagrean/data/product.txt
OrdersTxt=/Users/zagreansonia/Desktop/MAP/labs/a3-soniazagrean/data/order.txt

ProductsJson=/Users/zagreansonia/Desktop/MAP/labs/a3-soniazagrean/data/product.json
OrdersJson=/Users/zagreansonia/Desktop/MAP/labs/a3-soniazagrean/data/order.json

ProductsXml=/Users/zagreansonia/Desktop/MAP/labs/a3-soniazagrean/data/product.xml
OrdersXml=/Users/zagreansonia/Desktop/MAP/labs/a3-soniazagrean/data/order.xml

