Repository=nosql
LaunchType=gui
JdbcUrl=jdbc:sqlite:./data/electronics.db
ProductsBin=./data/product.bin
OrdersBin=./data/order.bin
ProductsTxt=./data/product.txt
OrdersTxt=./data/order.txt
ProductsJson=./data/product.json
OrdersJson=./data/order.json
ProductsXml=./data/product.xml
OrdersXml=./data/order.xml

